FROM mysql:5.7

RUN apt-get update
RUN apt-get install -y wget

RUN wget https://github.com/progrium/entrykit/releases/download/v0.4.0/entrykit_0.4.0_linux_x86_64.tgz
RUN tar -xvzf entrykit_0.4.0_linux_x86_64.tgz
RUN rm entrykit_0.4.0_linux_x86_64.tgz
RUN mv entrykit /usr/local/bin/
RUN entrykit --symlink

COPY add-server-id.sh /usr/local/bin/
COPY etc/mysql/mysql.conf.d/mysqld.cnf /etc/mysql/mysql.conf.d/
COPY prepare.sh /docker-entrypoint-initdb.d
COPY init-data.sh /usr/local/bin/
COPY sql /sql

ENTRYPOINT [ \
    "prehook", \
    "add-server-id.sh", \
    "--", \
  "docker-entrypoint.sh" \
]

CMD ["mysqld"]

// nginx
FROM nginx: 1.13

run apt-get update
run apt-get install -y wget

run wget https://github.com/progrium/entrykit/releases/download/v0.4.0/entrykit_0.4.0_linux_x86_64.tgz
run tar -xvzf entrykit_0.4.0_linux_x86_64.tgz
run mv entrykit /usr/local/bin/
run entrykit --symlink

RUN rm /etc/nginx/conf.d/*
COPY etc/nginx/nginx.conf.tmpl /etc/nginx/
COPY etc/nginx/conf.d /etc/nginx/conf.d/

ENTRYPOINT [ \
  "render", \
    "/etc/nginx/nginx.conf", \
    "--", \
  "render", \
    "/etc/nginx/nginx.conf", \
    "--", \
  "render", \
    "/etc/nginx/conf.d/public.conf", \
    "--", \
]

CMD ["nginx", "-g", "daemon off;"]




